platform :ios, '15.0'

# Improve CocoaPods performance
install! 'cocoapods', :disable_input_output_paths => true

target 'FaxApp' do
  use_frameworks!
  use_modular_headers!

pod 'CropViewController'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
